#!/bin/bash
# script script1-prep

bname=`basename $0`
echo "Major lab 1: bash script named $bname"

mkdir A1
mkdir A2
mkdir A3

cd A1
echo "file1" > file1
echo "file2" > file2
echo "file3" > file3
exit